spring:
  output.ansi.enabled: ALWAYS # ???? ? ????? ?????? ???? ????? ??????
  main:
    log-startup-info: true # ??????? ????????? ??????????
    banner-mode: console

  application.name: shareit

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate:
      format_sql: true
  sql:
    init.mode: always

  datasource:
    username: "shareit"
    password: "shareit"
    url: "jdbc:postgresql://localhost:6432/shareit"
    driver-class-name: "org.postgresql.Driver"

logging.level:
  ru:
    practicum:
      shareit: DEBUG
  org.springframework:
    orm.jpa: INFO
    orm.jpa.JpaTransactionManager: DEBUG
    transaction: INFO
    transaction.interceptor: TRACE

shareit:
  image-directory: images